site_name: eMBee Integration Blogs
site_url: https://matthiasblomme.github.io/blogs/

use_directory_urls: true

theme:
  name: material
  logo: assets/logo.jpg
  favicon: assets/logo.jpg
  features:
    - content.code.copy
    - naviagtion.sections
    - toc.follow
    - content.tags

plugins:
  - search


markdown_extensions:
  - meta
  - attr_list

nav:
  - Home: index.md
  - Posts:
      - All posts: posts/index.md
      - Archive: posts/archive.md
  - About: about.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/matthiasblomme
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/matthiasblomme/
      name: LinkedIn

extra_css:
  - assets/extra.css
